### ISSUE TITLE
call setInterval() method will cause an error,then the chip restart. 

### ISSUE THREAD

**Issue by fg607** [simenkid/nodemcu-timer#3]
There is no specific error shown when call setInterval() method,just like this:

 �5�4����T�{,��N��

and the chip will restart.
But,call setTimeout() method that is ok , need your help,thanks!

**Comment by simenkid** [comment]
Hello, may you try the [v1.0.0 release](https://github.com/simenkid/nodemcu-timer/releases/tag/v1.0.0)?
And how fast do you set with setInterval()?

**Comment by fg607** [comment]
@simenkid Thanks your reply,i have tried the v1.0.0 release ,but it's the same.
And i just set setInterval() once.

**Comment by simenkid** [comment]
It's weird. I didn't encounter such a problem. May I see your code?

**Comment by fg607** [comment]
`
function setTimer(deviceID)

```
local timer_id = getTimerId()

if poweron then
    timer.setInterval(function() print("interval") end,tonumber(interval))
else
    tmr.alarm(timer_id , interval, tmr.ALARM_AUTO, function() power(deviceID,"OFF") end )
end

return timer_id
```

end`

**Comment by simenkid** [comment]
I think there maybe a problem raised from `tonumber(interval)`. Where is the `interval`, from closure? You can try to replace `tonumber(interval)` with an integer, like `1000`, to test if the setInterval() can work well. 

It might be `tonumber(interval)` issue, I guess. Try to print it out, and see what happen?

**Comment by fg607** [comment]
Maybe that's not the real reason,because i have used the integer first time. The reason why i used tonumber() is that "timer" seems like can not convert string to interger automatically ,but "tmr" can.why? this is lua! 
does setInterval() consume too much memory？

**Comment by simenkid** [comment]
oops. The memory is a problem indeed, but depends how many tasks you scheduled. If it really is the memory issue, there is nothing I can do about that. Hardware resource is so tight, and cost is always there. 

I was using nodemcu-timer and lua-events modules on my LWM2M project. Guess what, memory is just not enough. It's not about the nodemcu-timer and lua-events, I can't even implement the LWM2M interfaces on ESP8266. XDD....  Then, I changed my mind, and now I use MTK Linkit Smart 7688 on my projects.

**Comment by fg607** [comment]
yes!  I also have found the limit of the ESP8266. The biggest problem for me is that the maximum value of interval  is 6870947ms with tmr.interval(),but i want  a 24 hours alarm clock. And it's  2147483647 ms (~25 days) with timer.setInterval(), could you tell me how to do that?

**Comment by simenkid** [comment]
Let me show you the hack if you'd like to use timer.setInterval().
At the very beginning of the source code (timer.lua), you will find a variable named `tick` which means the duration of timer ticking. Default is 2 ms per tick.

![tick](https://cloud.githubusercontent.com/assets/7709608/17285410/16983c62-57f5-11e6-97ab-1dd8ea9dc750.png)

You can change `tick` to any value that fits your need, such as 1000. Then you will get the duration of **1 second per tick**. Now you call `timer.setInterval(your_task, 60)`, and then you task will be fired every 60 seconds. I'm not sure if this is what you want? :-)

**Comment by fg607** [comment]
@simenkid  I know what you mean, the " exeque loop" method  is excellent,  that's helpful.  
Thank you very  much!

**Comment by fg607** [comment]
I delete all my code except timer.setInterval(), and it runs perfectly.

**Comment by simenkid** [comment]
Cool! It's nice to hear good news from you! Cheers!
Shall we close this issue? ^^

**Comment by fg607** [comment]
Yes, of course. Thanks again!
